# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'DrWatson' do



source 'https://github.com/CocoaPods/Specs.git'
pod 'IMFGoogleAuthentication'
pod 'IMFFacebookAuthentication'
pod 'IMFPush'
pod 'IMFData'
pod 'IMFURLProtocol'
pod 'IMFCore'

end

target 'DrWatsonTests' do

end

